### ISSUE TITLE
v6.8 build errors for Alpine Linux (musl libc)

### ISSUE THREAD

**Issue by Head-on-a-Stick** [ibara/oksh#49]
I'm trying to compile the new 6.8 release for [Alpine Linux's testing repositories](https://pkgs.alpinelinux.org/packages?name=oksh&branch=edge) but it won't build.

Configured with
```
./configure --prefix=/usr --bindir=/bin
```
Output:
```
checking for C compiler... cc                                                                                          
checking if C compiler can compile C99 without -std=c99... yes                                                         
checking for -w compiler flag... yes                                                                                   
checking for OS... Linux                                                                                               
checking for -flto compiler flag... not enabled                                                                        
checking for __dead... no                                                                                              
checking for __dead2... no                                                                                             
checking for __attribute__((__noreturn__))... yes                                                                      
checking for asprintf... yes                                                                                           
checking for clock_gettime in libc... yes                                                                              
checking for confstr... yes                                                                                            
checking for curses library... not found                                                                               
oksh will be built without screen clearing support                                                                     
checking for issetugid... yes                                                                                          
checking for pledge... no                                                                                              
checking for reallocarray... no                                                                                        
checking for setresgid... yes                                                                                          
checking for setresuid... yes                                                                                          
checking for sig_t... yes                                                                                              
checking for srand_deterministic... no                                                                                 
checking for st_mtim... yes                                                                                            
checking for st_mtimespec... no                                                                                        
checking for stravis... no                                                                                             
checking for strlcat... yes                                                                                            
checking for strlcpy... yes                                                                                            
checking for strtonum... no                                                                                            
checking for strunvis... no                                                                                            
checking for sys_siglist... no                                                                                         
checking for sys_signame... no                                                                                         
checking for timeradd... yes                                                                                           
checking for timersub... yes                                                                                           
creating Makefile... done
```
Then attempted a build with
```
make
```
Output:
```
cc -DEMACS -DVI -w -D_GNU_SOURCE   -c -o alloc.o alloc.c                                                               
cc -DEMACS -DVI -w -D_GNU_SOURCE   -c -o asprintf.o asprintf.c                                                         
cc -DEMACS -DVI -w -D_GNU_SOURCE   -c -o c_ksh.o c_ksh.c                                                               
cc -DEMACS -DVI -w -D_GNU_SOURCE   -c -o c_sh.o c_sh.c                                                                 
cc -DEMACS -DVI -w -D_GNU_SOURCE   -c -o c_test.o c_test.c                                                             
cc -DEMACS -DVI -w -D_GNU_SOURCE   -c -o c_ulimit.o c_ulimit.c                                                         
cc -DEMACS -DVI -w -D_GNU_SOURCE   -c -o edit.o edit.c                                                                 
cc -DEMACS -DVI -w -D_GNU_SOURCE   -c -o emacs.o emacs.c                                                               
cc -DEMACS -DVI -w -D_GNU_SOURCE   -c -o eval.o eval.c                                                                 
cc -DEMACS -DVI -w -D_GNU_SOURCE   -c -o exec.o exec.c                                                                 
cc -DEMACS -DVI -w -D_GNU_SOURCE   -c -o expr.o expr.c                                                                 
cc -DEMACS -DVI -w -D_GNU_SOURCE   -c -o history.o history.c                                                           
cc -DEMACS -DVI -w -D_GNU_SOURCE   -c -o io.o io.c                                                                     
cc -DEMACS -DVI -w -D_GNU_SOURCE   -c -o jobs.o jobs.c                                                                 
cc -DEMACS -DVI -w -D_GNU_SOURCE   -c -o lex.o lex.c                                                                   
cc -DEMACS -DVI -w -D_GNU_SOURCE   -c -o mail.o mail.c                                                                 
cc -DEMACS -DVI -w -D_GNU_SOURCE   -c -o main.o main.c                                                                 
cc -DEMACS -DVI -w -D_GNU_SOURCE   -c -o misc.o misc.c                                                                 
cc -DEMACS -DVI -w -D_GNU_SOURCE   -c -o path.o path.c                                                                 
cc -DEMACS -DVI -w -D_GNU_SOURCE   -c -o shf.o shf.c                                                                   
cc -DEMACS -DVI -w -D_GNU_SOURCE   -c -o syn.o syn.c                                                                   
cc -DEMACS -DVI -w -D_GNU_SOURCE   -c -o table.o table.c                                                               
cc -DEMACS -DVI -w -D_GNU_SOURCE   -c -o trap.o trap.c
cc -DEMACS -DVI -w -D_GNU_SOURCE   -c -o tree.o tree.c
cc -DEMACS -DVI -w -D_GNU_SOURCE   -c -o tty.o tty.c
cc -DEMACS -DVI -w -D_GNU_SOURCE   -c -o var.o var.c
cc -DEMACS -DVI -w -D_GNU_SOURCE   -c -o version.o version.c
cc -DEMACS -DVI -w -D_GNU_SOURCE   -c -o vi.o vi.c
vi.c: In function 'vi_insert':
vi.c:627:2: error: case label does not reduce to an integer constant
  627 |  case CTRL('['):
      |  ^~~~
vi.c:645:2: error: case label does not reduce to an integer constant
  645 |  case CTRL('x'):
      |  ^~~~
vi.c:649:2: error: case label does not reduce to an integer constant
  649 |  case CTRL('f'):
      |  ^~~~
vi.c:653:2: error: case label does not reduce to an integer constant
  653 |  case CTRL('e'):
      |  ^~~~
vi.c:657:2: error: case label does not reduce to an integer constant
  657 |  case CTRL('l'):
      |  ^~~~
vi.c:661:2: error: case label does not reduce to an integer constant
  661 |  case CTRL('i'):
      |  ^~~~
vi.c: In function 'vi_cmd':
vi.c:717:3: error: case label does not reduce to an integer constant
  717 |   case CTRL('l'):
      |   ^~~~
vi.c:721:3: error: case label does not reduce to an integer constant
  721 |   case CTRL('r'):
      |   ^~~~
vi.c:894:3: error: case label does not reduce to an integer constant
  894 |   case CTRL('n'):
      |   ^~~~
vi.c:905:3: error: case label does not reduce to an integer constant
  905 |   case CTRL('p'):
      |   ^~~~
vi.c:1137:3: error: case label does not reduce to an integer constant
 1137 |   case CTRL('e'):   /* Nonstandard vi/ksh */
      |   ^~~~
vi.c:1142:3: error: case label does not reduce to an integer constant
 1142 |   case CTRL('i'):   /* Nonstandard vi/ksh */
      |   ^~~~
vi.c:1148:3: error: case label does not reduce to an integer constant
 1148 |   case CTRL('['):   /* some annoying at&t ksh's */
      |   ^~~~
vi.c:1152:3: error: case label does not reduce to an integer constant
 1152 |   case CTRL('f'):   /* Nonstandard vi/ksh */
      |   ^~~~
vi.c:1158:3: error: case label does not reduce to an integer constant
 1158 |   case CTRL('x'):   /* Nonstandard vi/ksh */
      |   ^~~~
vi.c: In function 'domove':
vi.c:1218:2: error: case label does not reduce to an integer constant
 1218 |  case CTRL('h'):
      |  ^~~~
make: *** [<builtin>: vi.o] Error 1
```
I'm not a programmer so I can't make much sense of the problem, sorry.

FWIW the new version built fine for Debian, build log for that (stable x86_64 version) here:

https://build.opensuse.org/package/live_build_log/home:Head_on_a_Stick:oksh/oksh/Debian_10/x86_64

**Comment by ibara** [comment]
I think I found the issue.
If you add
`#define CTRL(c)		(c & 0x1f)`
to the top of vi.c (right after all the #includes), does this fix compilation?

**Comment by dgoerger** [comment]
I'm not the OP, but I can confirm this fixes the build on both Alpine Linux 3.12.1, Debian 10, and NetBSD 9.1. I was too tired last night to file a bug report but logged on this morning to report the same build failure.

**Comment by ibara** [comment]
Cool. So it looks like musl is missing that define for some reason.

**Comment by ibara** [comment]
It would be nice if the CI system had a musl-libc build tester...
