### ISSUE TITLE
doesn't build on FreeBSD 10.4 after eb2e0676cd162af963a3cb2fad48ba3f458b4c4c

### ISSUE THREAD

**Issue by tjackson** [ibara/oksh#12]
Hi there,

I can build this with FreeBSD 10.4 at commit eb2e0676cd162af963a3cb2fad48ba3f458b4c4c but only with gmake, as make doesn't know how to build the man pages.

After that commit I see an error about missing charclass.h or with gmake an undefined reference to stravis, respectively:

misc.c:16:10: fatal error: 'charclass.h' file not found

history.o: In function `histsave':
history.c:(.text+0x1610): undefined reference to `stravis'
history.o: In function `history_write':
history.c:(.text+0x18ee): undefined reference to `stravis'

Unfortunately I don't know how to suggest fixing it. I'm just an amateur to BSDs but I really liked this shell when I was trying out OpenBSD.

Thanks,
Tod

**Comment by tjackson** [comment]
I don't know what the hell I'm doing but it builds and runs with this nonsense:

diff --git a/history.c b/history.c
index bea1b16..81a879a 100644
--- a/history.c
+++ b/history.c
@@ -27,6 +27,10 @@
 #include <vis.h>
 #endif
 
+#ifdef __FreeBSD__ == 10
+#define SMALL
+#endif
+
 #include "sh.h"
 
 #ifdef HISTORY
diff --git a/misc.c b/misc.c
index c1a6006..93b1733 100644
--- a/misc.c
+++ b/misc.c
@@ -13,7 +13,10 @@
 #include <unistd.h>
 
 #include "sh.h"
-#include "charclass.h"
+
+#ifdef __FreeBSD__ == 10
+#include "portable/common/charclass.h"
+#endif
 
 short ctypes [UCHAR_MAX+1];    /* type bits for unsigned char */

;-)

**Comment by ibara** [comment]
Two things:
1. You should only build this with `gmake`.

2. Your issue should be fixed now.
The real issue was that FreeBSD and DragonFly BSD, like Mac OS X, don't have a `stravis()` function in their `libc` so they have to use the portable version.
